# This service requests a node to provide the message identifiers and timestamps
# for all published messages.

---

# A map of topic names to their message identifiers and timestamps
MessageIdWithTimestamps[] received_message_timestamps

# Topic names
string[] received_topic_names


MessageInfo[] published_messages

string[] published_topic_names

# True if no error occurred
bool success false

# Lifecycle state transitions (state name and timestamp)
LifecycleTransition[] lifecycle_transitions
